Color gradient picker
mue/mue pull request #115
Opened 2020-10-22 01:08 UTC by MrOnosa

Integrated the react-color-gradient-picker from https://www.npmjs.com/package/react-color-gradient-picker

2020-10-26 15:12 UTC, ohlookitsderpy commented
Hello again! Sorry this review is later than usual, I was away.

The circle looks worse than normal now:
(New)
![image](https://user-images.githubusercontent.com/14052956/97189711-cc02ba80-179c-11eb-9c66-220fb47de148.png)

(Old)
![image](https://user-images.githubusercontent.com/14052956/97189726-d1600500-179c-11eb-8ff8-f46a2bd4b7c6.png)

I can't seem to find a way to go back to having just 1 colour on normal colour picker anymore:
![image](https://user-images.githubusercontent.com/14052956/97189837-efc60080-179c-11eb-8020-0e04dcecd9d8.png)

The text colour on the picker is different to normal as well and the padding is off compared to the rest of the items:
![image](https://user-images.githubusercontent.com/14052956/97189917-08ceb180-179d-11eb-9597-ef103157027c.png)

Not sure how to show this in a screenshot, but I don't know how to remove the various stops on the picker, or how to remove the initial one (all the gradients I create have a white bit at the bottom/top).

Finally, I think it would be good if we somehow add text to the various functions of the picker as the functions are rather complex to use.

Thank you!

2020-10-29 11:32 UTC, ohlookitsderpy requested changes
Just some small code-style tweaks that need doing as well before this can be merged

2020-10-29 11:32 UTC, ohlookitsderpy commented on src/components/modals/settings/Section.jsx
> +    if(this.props.onToggle) {
Please add a space after "if"

2020-10-29 11:32 UTC, ohlookitsderpy commented on src/components/modals/settings/sections/BackgroundSettings.jsx
> +  mapFromGradientSettingsToColorPickerInitalState(gradientSettings) {
This function name is very long

2020-10-29 11:32 UTC, ohlookitsderpy commented on src/components/modals/settings/sections/BackgroundSettings.jsx
> +    if(process.env.NODE_ENV == 'development'){
space after "if" here as well

2020-10-29 11:32 UTC, ohlookitsderpy commented on src/helpers/hexToRgb.js
> +import  rgbToHsv  from './rgbToHsv';
Imports should only have 1 space after the import statement

2020-10-29 11:32 UTC, ohlookitsderpy commented on src/scss/index.scss
> +{
Please make this consistent with the other css

2020-10-29 11:32 UTC, ohlookitsderpy commented on src/components/widgets/Background.jsx
>        //Note: Append the gradient for additional browser support.
It's preferred to have a space after the // but not required

2020-10-29 11:32 UTC, ohlookitsderpy commented on src/components/modals/settings/sections/BackgroundSettings.jsx
> +import hexToRgb from '../../../../helpers/hexToRgb'
Missing semicolons

2020-10-31 00:38 UTC, MrOnosa commented on src/scss/index.scss
> +{
I wasn't really sure what you meant. But, please see react-color-picker-gradient-picker-custom-styles.scss for the updates.

2020-10-31 00:42 UTC, MrOnosa commented
> I can't seem to find a way to go back to having just 1 colour on normal colour picker anymore:

Use the Reset button.

---

>  I don't know how to remove the various stops on the picker

Select a stop and press the Delete key

---

> or how to remove the initial one

Gradients require at least two stops so we cannot delete beyond that by design. You can drag the initial one around. I am able to get it to start at 0 (the very beginning)

2020-10-31 11:26 UTC, ohlookitsderpy approved these changes

2020-10-31 11:29 UTC, ohlookitsderpy commented
Somehow I didn't think of using the delete key and reset button 😂 I was asking about the initial one as I couldn't originally seem to get it to change colour from white, but now I can.


Anyways, thank you! LGTM 👍

2020-10-31 11:29 UTC, merged